#import pinelib as pl
import pinelib.series as pls
import pinelib.math as plm

test_serie = pls.Serie([1, 2, 3, 4, 5])
print(test_serie)
print(test_serie[2])
print('Add S+S', test_serie + test_serie[2])
print('Add S+I', test_serie + 2)
print('Sub S-S', test_serie - test_serie[2])
print('Sub S-I', test_serie - 2)
print('FDiv S//S', test_serie // test_serie[2])
print('FDiv S//I', test_serie // 2)
print('TDiv S/S', test_serie / test_serie[2])
print('TDiv S/I', test_serie / 2)
print('Mul S*S', test_serie * test_serie[2])
print('Mul S*I', test_serie * 2)
print('Mod S%S', test_serie % test_serie[2])
print('Mod S%I', test_serie % 2)
print('Pow S**S', test_serie ** test_serie[2])
print('Pow S**I', test_serie ** 2)

print('First Serie:', pls.Serie([1, 2, 3, 4, 5]))
print('Second Serie:', pls.Serie([1, 1, 1, 1, 1, 1, 1, 1]))
print('Answer', pls.Serie([1, 2, 3, 4, 5]) + pls.Serie([1, 1, 1, 1, 1, 1, 1, 1]))
test_serie2 = pls.Serie([1, 1, 1, 1, 1, 1])
print('Before iadd:', test_serie2)
test_serie2 += test_serie
print('After iadd:', test_serie2)

print('\n\n\nMath:')
print(test_serie)
print('e', plm.e)
print('pi', plm.pi)
print('phi', plm.phi)
print('rphi', plm.rphi)
print('math.abs', plm.abs(test_serie))
print('math.acos', plm.acos(test_serie))
print('math.asin', plm.asin(pls.Serie([0.0, 0.2, 0.4, 0.6, 0.8, 1])))
print('math.atan', plm.atan(test_serie))
print('math.avg', plm.avg(test_serie))
print('math.sum', plm.sum(test_serie))
print('math.sqrt', plm.sqrt(test_serie))
print('math.pow', plm.pow(test_serie, 2))
print('math.min', plm.min(test_serie))
print('math.max', plm.max(test_serie))
print('math.exp', plm.exp(test_serie))
print('math.cos', plm.cos(test_serie))
print('math.cos -> math.abs', plm.abs(plm.cos(test_serie)))